# Generated by Django 2.0.6 on 2019-02-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(blank=True, max_length=254, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('numero_processo', models.CharField(blank=True, max_length=254, null=True)),
                ('ato', models.CharField(blank=True, max_length=254, null=True)),
                ('tipo_acao', models.CharField(blank=True, max_length=254, null=True)),
                ('data_publicacao_ato', models.DateTimeField(blank=True, null=True)),
                ('autor', models.CharField(blank=True, max_length=254, null=True)),
                ('reu', models.CharField(blank=True, max_length=254, null=True)),
                ('advogado', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Processo',
            },
        ),
    ]
