# Generated by Django 2.0.6 on 2019-02-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_processo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição')),
                ('documento', models.FileField(blank=True, null=True, upload_to='', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Arquivos',
            },
        ),
    ]
