# Generated by Django 2.0.6 on 2019-02-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_arquivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivos',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
