# Generated by Django 2.0.6 on 2019-02-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_arquivos_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição')),
                ('texto', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ato',
            },
        ),
    ]
