# Generated by Django 2.0.6 on 2019-02-24 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_ato'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='client.Usuario'),
        ),
    ]
